version: '{branch}-{build}'
build: off
image:
- Visual Studio 2015
environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
{% for env, config in tox_environments|dictsort %}{% if not config.cover %}
    - TOXENV: '{{ config.python[-3:] }}-buildonly-nocover'
      TOXPYTHON: C:\{{ config.python.replace('.', '') }}\python.exe
      WINDOWS_SDK_VERSION: v7.{{ '1' if config.python[-3] == '3' else '0' }}
      PYTHON_HOME: C:\{{ config.python.replace('.', '') }}
      PYTHON_VERSION: '{{ config.python[-3:] }}'
      PYTHON_ARCH: '32'
    - TOXENV: '{{ config.python[-3:] }}-buildonly-nocover'
      TOXPYTHON: C:\{{ config.python.replace('.', '') }}-x64\python.exe
      WINDOWS_SDK_VERSION: v7.{{ '1' if config.python[-3] == '3' else '0' }}
      PYTHON_HOME: C:\{{ config.python.replace('.', '') }}-x64
      PYTHON_VERSION: '{{ config.python[-3:] }}'
      PYTHON_ARCH: '64'
{% endif %}{% endfor %}
    - TOXENV: check
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
{% for env, config in tox_environments|dictsort %}{% if config.python in ('python2.7', 'python3.6', 'python3.7', 'python3.8',) and not config.cover %}
    - TOXENV: '{{ env }}{% if config.cover %},codecov{% endif %}'
      TOXPYTHON: C:\{{ config.python.replace('.', '') }}\python.exe
      PYTHON_HOME: C:\{{ config.python.replace('.', '') }}
      PYTHON_VERSION: '{{ config.python[-3:] }}'
      PYTHON_ARCH: '32'
    - TOXENV: '{{ env }}{% if config.cover %},codecov{% endif %}'
      TOXPYTHON: C:\{{ config.python.replace('.', '') }}-x64\python.exe
      WINDOWS_SDK_VERSION: v7.{{ '1' if config.python[-3] == '3' else '0' }}
      PYTHON_HOME: C:\{{ config.python.replace('.', '') }}-x64
      PYTHON_VERSION: '{{ config.python[-3:] }}'
      PYTHON_ARCH: '64'
{% endif %}{% endfor %}
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'

after_test:
### if tagged commit, build/upload wheel
#  - IF "%TOXENV%"=="2.7-buildonly-nocover" IF "%PYTHON_ARCH%"=="32" (%WITH_COMPILER% %TOXPYTHON% setup.py sdist)
### Twine commands not working, remove for now
#  - IF "%APPVEYOR_REPO_TAG%"=="true" IF NOT "%TOXENV%"=="%TOXENV:buildonly=%" (
#      %WITH_COMPILER% %TOXPYTHON% setup.py bdist_wheel &&
#      %PYTHON_HOME%\Scripts\pip install twine &&
#      %PYTHON_HOME%\Scripts\twine upload -u %PYPI_USER% -p %PYPI_PASS% dist/*
#    )

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*
matrix:
  allow_failures:
    - TOXENV: '2.7-nocover'
    - TOXENV: '3.7-nocover'
### To enable remote debugging uncomment this:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

